/**
 * Validation methods
 * - equals
 * - notEquals
 * - contains
 * - notContains
 * - isNumber
 * - isString
 * - isBoolean
 * - isDate
 * - isEmail
 * - isUrl
 * - isIP
 * - isIPv4
 * - isIPv6
 * - smallerThan
 * - greaterThan
 * - smallerOrEqualsThan
 * - greaterOrEqualsThan
 * - isMatch(regex)
 * - isNotMatch(regex)
 * - isNull
 * - isNotNull
 * - isUndefined
 * - isNotUndefined
 * - isFunction
 * - isNotFunction
 * - isArray
 * - isNotArray
 * - isObject
 * - isNotObject
 */
